### ISSUE TITLE
Unresponsive to Night Mode or Dark Style switches

### ISSUE THREAD

**Issue by Inderix** [tuberry/user-theme-x#11]
Configuring the extension and testing it shows no visual change besides GNOME itself automatically changing the wallpaper per it's default capabilities 
I've attached a video presenting more clearly the issue. Expected outcome is to see the shell, icon, GTK3 and cursor themes change as soon as Night Mode was enabled, instead nothing seems to occur. It's also worth noting that within the settings enabling Night Mode will automatically force the left "style" selection to prefer-light or prefer-dark in tandem with enabling and disabling night mode.
[Screencast from 2023-09-19 14-14-54.webm](https://github.com/tuberry/user-theme-x/assets/88416096/f7170a8e-1fdd-4841-ad08-30b1e9d44be4)

**Comment by tuberry** [comment]
> I've attached a video presenting more clearly the issue. Expected outcome is to see the shell, icon, GTK3 and cursor themes change as soon as Night Mode was enabled, 

This seems to be the expected behavior: switching themes when the Night Light become active/inactive (usually at dusk or dawn), provided that the Night Light is enabled. You can manually adjust the night light time to see if it works:
[night-light-screencast.webm](https://github.com/tuberry/user-theme-x/assets/17917040/023ac8a2-f1d4-4214-9f27-8a71807a6ea2)

> It's also worth noting that within the settings enabling Night Mode will automatically force the left "style" selection to prefer-light or prefer-dark in tandem with enabling and disabling night mode.

It's also expected. The extension will automatically modify the system settings. When the user manually changes the system settings, the changes should be synchronized to the extension side, respectively.  :)

The only odd thing is that the `Dark Style` doesn't affect libadwaita apps (such as the extension settings window in your screencast), but that should be irrelevant to this extension.
