### ISSUE TITLE
Enhancement: Switch themes based on Style (prefer-dark, prefer-light)

### ISSUE THREAD

**Issue by grandant** [tuberry/user-theme-x#14]
Hi, thanks for the great extension.

I was working on a app with similar functionality based on [AutomaThemely](https://github.com/C2N14/AutomaThemely) since [Night Theme Switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) dropped the functionality.

Anyway, is it possible to add the option to switch themes based on current style. I already use Night Theme Switcher to change styles automatically. Using your extension with the Night Light status will lead to inconsistencies.

Thanks in advance. Cheers!

**Comment by tuberry** [comment]
Sorry, but this feature is not compatible with this extension. :(

1. Style is tri-state(prefer-dark/prefer-light/default) instead of the current two-state (dark/light), so this feature (especially switching between Style and NightLight) will definitely complicate the UI.

2. The goal of this extension is to be as set-and-forget as possible, while this feature relies on manual toggling or another [extension](https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension#frequently-asked-questions).
